[flavor]
dark = "catppuccin-mocha"

# : Manager {{{
[mgr]
border_symbol = ''
border_style = { fg = "#1E2031" } # border style.
# : }}}

# : Mode {{{
[mode]
normal_main = { fg = "#282C34", bg = "#61AFEF", bold = true } # Dark gray on Blue
normal_alt = { fg = "#61AFEF", bg = "#282C34", bold = true }  # Dark gray on Blue
select_main = { fg = "#282C34", bg = "#98C379", bold = true }
select_alt = { fg = "#98C379", bg = "#282C34", bold = true }
unset_main = { fg = "#282C34", bg = "#E06C75", bold = true }
unset_alt = { fg = "#E06C75", bg = "#282C34", bold = true }
# : }}}

# : Status {{{
[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
# : }}}

# : Filetype {{{
[filetype]
rules = [
	# Image
	{ mime = "image/*", fg = "#E5C07B" },
	# Media
	{ mime = "{audio,video}/*", fg = "#E06C75" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#C678DD" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#98C379" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#949CBB" },
	# Fallback
	{ url = "*", fg = "#ABB2BF" },
	{ url = "*/", fg = "#61AFEF" },
]
# : }}}
